export const REQUEST_CARDS = "REQUEST_CARDS";
export const RECEIVE_CARDS = "RECEIVE_CARDS";
export const UPDATE_CARDS = "UPDATE_CARDS";
export const SET_FILTERS = "SET_FILTERS";
export const SET_FILTER_APPLIED = "SET_FILTER_APPLIED";
